hbgd_data_store_server/urls.py
# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""hbgd_data_store_server URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView

from .views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^studies/', include('studies.urls')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^docs/', include('docs.urls')),
    url(r'^robots.txt',
        RedirectView.as_view(url=settings.STATIC_URL + 'robots.txt', permanent=False),
        name="robot"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

studies/urls.py
# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import url

from .views import (
    ExportByAgeView,
    ExportView,
    StudyListView,
    StudyFilterView,
    StudyExplorerView,
    VariableListView,
)

urlpatterns = [
    url(r'^list$', StudyListView.as_view(), name='study-list'),
    url(r'^filter$', StudyFilterView.as_view(), name='study-filter'),
    url(r'^variables/(?P<domain_code>[-\S]+)', VariableListView.as_view(), name='variable-list'),
    url(r'^explorer', StudyExplorerView.as_view(), name='study-explorer'),
    url(r'^export/domain_(?P<domain_id>[0-9]+)', ExportView.as_view(), name='export'),
    url(r'^export_by_age/domain_(?P<domain_id>[0-9]+)', ExportByAgeView.as_view(), name='export_by_age'),  # noqa
]

studies/forms.py
# Copyright 2017-present, Bill & Melinda Gates Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import itertools
from collections import OrderedDict

from django import forms
from django.db.models import Case, When, Value, BooleanField

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Div
from crispy_forms_foundation.layout import Layout, Fieldset
from crispy_forms_foundation.layout.containers import AccordionHolder, AccordionItem
from crispy_forms_foundation.layout.fields import InlineField, Field
from crispy_forms_foundation.layout.buttons import Submit, ButtonGroup
from crispy_forms_foundation.layout.grid import Row, Column

from .fields import (EmptyChoiceField, RangeField, DiscreteRangeField,
                     ExtendedMultipleChoiceField)
from .models import Study, Filter, Variable


class VariableListForm(forms.Form):
    category = EmptyChoiceField(required=False, empty_label="Search by Category")
    variable = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search by Variable'}
        ),
    )

    def __init__(self, *args, **kwargs):
        self._request = kwargs.pop('request')
        self._domain = kwargs.pop('domain')

        super(VariableListForm, self).__init__(*args, **kwargs)

        variables = Variable.objects.filter(domain=self._domain)

        # set category choices based on variable categories or disable field if None
        if not variables.exclude(category=None):
            self.fields['category'].disabled = True
        else:
            choices = list(variables.values_list('category', 'category')
                                    .distinct()
                                    .order_by('category'))
            self.fields['category'].choices = tuple(self.fields['category'].choices + choices)

        # set initial form fields based on request
        self.initial = dict(category=self._request.GET.get('category'),
                            variable=self._request.GET.get('variable'))

        # sorted, unique list of variable codes and labels for autocomplete tip
        self.variable_autocomplete_options = sorted(set(itertools
                                                    .chain(*variables
                                                        .values_list(
                                                            'code', 'label'))))

        self.helper = FormHelper()
        self.helper.form_method = "GET"
        self.helper.layout = Layout(
            Row(
                Column(
                    InlineField('category', label_class="hide", input_column="small-12"),
                    css_class="small-4",
                ),
                Column(
                    InlineField('variable', label_class="hide", input_column="small-12"),
                    css_class="small-8",
                )
            ),
            Row(
                Column(
                    ButtonGroup(
                        Submit('Submit', 'Submit', css_class="tiny"),
                        Submit('Reset', 'Clear Filters', css_class="secondary tiny")
                    )
                )
            ),
        )


class StudyExplorerForm(forms.Form):
    study = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=Study.objects.all().order_by('study_id'),
        label=False
    )
    search = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Select Study by Name'}
        ),
    )

    def __init__(self, *args, **kwargs):
        self._request = kwargs.pop('request')

        super(StudyExplorerForm, self).__init__(*args, **kwargs)

        # Returns [-1] if None because `annotate` method will return empty queryset if ids = []
        ids = self._request.GET.getlist('study', [-1])
        studies = Study.objects.annotate(
            is_active=Case(When(id__in=ids, then=Value(True)),
                           default=Value(False),
                           output_field=BooleanField())
        )
        self.fields["study"].queryset = studies.order_by('-is_active', 'study_id')

        self.initial = {"study": ids}

        # JQuery UI autocomplete requires object with label and value attrs
        # Have to augment id value by one because input checkbox ids start at one
        self.search_autocomplete_options = [
            dict(label=k['study_id'], value=k['study_id'], id=i + 1)
            for i, k in enumerate(self.fields["study"].queryset.values('id', 'study_id'))
        ]

        self.helper = FormHelper()
        self.helper.form_method = "GET"
        self.helper.layout = Layout(
            Row(
                Column(
                    InlineField('search', label_class="hide", input_column="small-12"),
                    css_class="small-12",
                )
            ),
            Row(
                Column(
                    Div(
                        HTML('<span id="message-bar">No new filters.</span>'),
                        ButtonGroup(
                            Submit('Apply', 'Apply', css_class="tiny secondary"),
                            Submit('Reset', 'Clear Filters', css_class="secondary tiny"),
                            css_class="right",
                        )
                    )
                ),
                css_id="sticky-menu"
            ),
            Row(
                Column(
                    Fieldset("Studies", 'study')
                ),
            ),
        )


class StudyFilterForm(forms.Form):
    accordion_template = 'forms/accordion-holder.html'
    range_template = 'forms/range-widget.html'
    domain_template = 'forms/domain-widget.html'

    def __init__(self, *args, **kwargs):
        self._request = kwargs.pop('request')

        super(StudyFilterForm, self).__init__(*args, **kwargs)

        self.applied_filters = []

        layouts = OrderedDict([('Study', []), ('Qualifier', []), ('Domain', [])])
        for filt in Filter.objects.all().order_by('label'):
            layout_item, form_field = self._get_filter_layout_and_field(filt)
            # put layout_item into correct layout_group
            layouts[filt.filter_type].append(layout_item)
            # register form_field in form fields
            self.fields[filt.name] = form_field
            # add pretty_initial values to form attr if exists (for view)
            if hasattr(form_field, 'pretty_initial'):
                self.applied_filters.append((filt.label, form_field.pretty_initial))

        study_layout = self._get_accordion_or_empty(items=layouts['Study'])
        qualifier_layout = self._get_accordion_or_empty(items=layouts['Qualifier'])
        domain_layout = self._get_accordion_or_empty(items=layouts['Domain'])

        self.helper = FormHelper()
        self.helper.form_method = "GET"
        self.helper.layout = Layout(
            Row(
                Column(
                    Div(
                        HTML('<span id="message-bar">No new filters.</span>'),
                        ButtonGroup(
                            Submit('Apply', 'Apply', css_class="tiny secondary"),
                            Submit('Reset', 'Clear Filters', css_class="secondary tiny"),
                            css_class="right",
                        )
                    )
                ),
                css_id="sticky-menu"
            ),
            Row(
                Column(
                    Fieldset("Study metadata", study_layout),
                )
            ),
            Row(
                Column(
                    Fieldset("Qualifier metadata", qualifier_layout),
                )
            ),
            Row(
                Column(
                    Fieldset("Domain metadata", domain_layout),
                )
            )
        )

    def _get_accordion_or_empty(self, items=()):
        if items:
            field = AccordionHolder(*items, template=self.accordion_template)
        else:
            field = HTML("Please contact your administrator about adding a filter.")
        return field

    def _get_filter_layout_and_field(self, filt):
        """
        Initializes the appropriate crispy form layout and form field
        object given a Filter.

        Parameters:
            filt: Filter
                A Filter model instance

        Returns:
            crispy_forms_foundation.layout.Field, django.forms.Field
        """

        layout_field = Field(filt.name)
        field_kwargs = dict(required=False, label=False)
        values = filt.get_values()

        if filt.widget == 'discrete slider':
            layout_field.template = self.range_template
            initial = filt.get_initial_slider_values(self._request.GET, values=values)
            field_kwargs.update(initial)
            choices = filt.get_choices(values=values)
            form_field = DiscreteRangeField(choices=choices,
                                            custom_json=filt.widget_json,
                                            **field_kwargs)

        elif filt.widget == 'double slider':
            layout_field.template = self.range_template
            initial = filt.get_initial_slider_values(self._request.GET)
            field_kwargs.update(initial)
            form_field = RangeField(min_value=values[0],
                                    max_value=values[-1],

studies/templates/studies/study_explorer.html
{% extends 'content.html' %}
{% load django_tables2 crispy_forms_tags humanize static %}

{% block extrahead %}
  {{ block.super }}
  <link href="{% static 'bower_components/bokeh/bokeh-0.12.3.min.css' %}" rel="stylesheet" type="text/css">
{% endblock extrahead %}

{% block content %}
<div class="row study-explorer">
  <div class="small-4 columns">
    <div class="sidebar">
      <div class="applied-filters">
        <h6>Applied filters</h6>
        <div class="panel">
          {% if applied_filters %}
            <ul class="inline-list">
            {% for filter_key, filter_value in applied_filters %}
              <li class="left"><strong>{{ filter_key }}</strong>{{ filter_value }}</li>
            {% endfor %}
            </ul>
          {% else %}
            <p>None</p>
          {% endif %}
          <div class="summary">
            <p class="left">{{ n_selected }} out of {{ n_total }} studies</p>
            {% if applied_filters %}
            <a class="right" href="{% url 'study-filter' %}?{{ request.META.QUERY_STRING }}">
              <strong>Edit filters</strong>
            </a>
            {% else %}
            <a class="right" href="{% url 'study-filter' %}">
              <strong>Add filters</strong>
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      {% crispy form form.helper %}
    </div>
  </div>
  <div class="small-8 columns buffer">
    <div class="summary-plot">
      {% if domains %}
        {{ plot_summary_div|safe }}
      {% else %}
        {% if n_studies > 0 %}
          The filtered studies have no data associated with them. Please contact your data administrator.
        {% else %}
          Please select a study from the list, or return to the <a href="{% url 'study-filter' %}">study filter</a> to find new studies.
        {% endif %}
      {% endif %}
    </div>
    {% comment %}The next two sections have a lot in common. Could be dried out?{% endcomment %}
    <div class="breakdown clearfix">
      {% if domains %}
      <h4>Breakdown by variable</h4>
      {% endif %}
      <ul class="tabs vertical" data-tab>
        {% for domain in domains %}
          <li class="tab-title {% if forloop.first %}active{% endif %}">
            <a href="#{{ domain.code }}_tab">{{ domain.label }}</a>
          </li>
        {% endfor %}
      </ul>
      <div class="tabs-content">
        {% for domain in domains %}
        <div class="content {% if forloop.first %}active{% endif %}" id="{{ domain.code }}_tab">
          <div class="plot-wrapper">
          {{ domain.heatmap|safe }}
          {% if n_selected > 0 and domain.heatmap %}
            <p>Total observations: {{ domain.count|intcomma }}</p>
            <p><a href="{% url 'export' domain_id=domain.id %}?{{ request.META.QUERY_STRING }}">Download data</a></p>
          {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="breakdown clearfix">
      {% if domains %}
      <h4>Breakdown by age</h4>
      {% endif %}
      <ul class="tabs vertical" data-tab>
        {% for domain in age_domains %}
          <li class="tab-title {% if forloop.first %}active{% endif %}">
            <a href="#{{ domain.code }}_tab_age">{{ domain.label }}</a>
          </li>
        {% endfor %}
      </ul>
      <div class="tabs-content">
        {% for domain in age_domains %}
        <div class="content {% if forloop.first %}active{% endif %}" id="{{ domain.code }}_tab_age">
          <div class="plot-wrapper">
          {{ domain.age_heatmap|default_if_none:"No breakdown by age"|safe }}
          {% if n_selected > 0 and domain.age_heatmap %}
            <p>Total observations: {{ domain.count|intcomma }}</p>
            <p><a href="{% url 'export_by_age' domain_id=domain.id %}?{{ request.META.QUERY_STRING }}">Download data</a></p>
          {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extrajavascript %}
{{ block.super }}
<script src="{% static 'bower_components/foundation/js/vendor/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'bower_components/jquery-ui/jquery-ui.js' %}" type="text/javascript" ></script>
<script src="{% static 'bower_components/jquery-sticky/jquery.sticky.js' %}"></script>
<script>
  $( "#id_search" ).autocomplete({
    source: {{ form.search_autocomplete_options|safe }},
    autoFocus: true,
    select: function(event, ui) {
      var checkbox = $("#id_study_" + ui.item.id)
      if (!checkbox.is(":checked")) checkbox.change();
      checkbox.prop('checked', true);
    },
  }).change();

  $("#sticky-menu").sticky({topSpacing:0, zIndex:100});

  function indicate_new_filters() {
    $("#sticky-menu").addClass("alert");
    $("#message-bar").text("New filters have been selected. Click Apply to refresh studies.");
  }

  $(":checkbox").on('change', indicate_new_filters);

  $(document).on('click.fndtn.accordion', '.accordion-navigation a', function (e) {
    var icon_id = e.currentTarget.firstElementChild.id;
    $( "#" + icon_id ).toggleClass("fa-angle-double-up");
    $( "#" + icon_id ).toggleClass("fa-angle-double-down");
  });
</script>
<script src="{% static 'bower_components/bokeh/bokeh-0.12.3.min.js' %}" type="text/javascript"></script>
<script src="{% static 'bower_components/bokeh/bokeh-widgets-0.12.3.min.js' %}"></script>
{{ plot_script|safe }}
{{ plot_age_script|safe }}
{{ plot_summary_script|safe }}
{% endblock extrajavascript %}

studies/templates/studies/study_filter.html
{% extends 'content.html' %}
{% load django_tables2 crispy_forms_tags keyvalue static %}

{% block extrahead %}
  {{ block.super }}
  <link href="{% static 'bower_components/bokeh/bokeh-0.12.3.min.css' %}" rel="stylesheet" type="text/css">
{% endblock extrahead %}

{% block page_title %} - Study Filter {% endblock page_title %}

{% block content %}
<div class="row">
  <div class="small-6 columns">
    <div class="sidebar">
      <div class="applied-filters">
        <h6>Applied filters</h6>
        <div class="panel">
          <ul class="inline-list">
            {% if study_form.applied_filters %}
              {% for filter_key, filter_value in study_form.applied_filters %}
                <li class="left"><strong>{{ filter_key }}</strong>{{ filter_value }}</li>
              {% endfor %}
            {% else %}
                <li class="left">None</li>
            {% endif %}
          </ul>
          <p>{{ paginator.count }} out of {{ n_total }} studies</p>
        </div>
      </div>
      <div id="form-parent">
        {% crispy study_form study_form.helper %}
      </div>
    </div>
	</div>
  <div class="small-5 columns buffer">
    <div class="summary-plot">
      {% if plot_summary_div %}
        {{ plot_summary_div|safe }}
      {% else %}
        The filtered studies have no data associated with them. Please contact your data administrator.
      {% endif %}
    </div>
    {% if filtered_studies|length > 0 %}
    {% include 'snippet_pagination.html' %}
      {% for obj in object_list %}
      <div class="panel">
        <h6>{{ obj.study_id }}</h6>
          {% if field_names %}
          {% with study_dict|keyvalue:obj.study_id as field_dict %}
          {% for field_name in field_names %}
            <p><b>{{ field_name }}</b>: {{ field_dict|keyvalue:field_name }}</p>
          {% endfor %}
          {% endwith %}
          {% endif %}
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="small-1 columns buffer">
    {% if filtered_studies %}
    <a title="View these studies in the study explorer" href="{% url 'study-explorer' %}?{{ GET_params }}">
      <span class="fa fa-chevron-right fa-3x">
    </a>
    {% else %}
      <span class="disabled fa fa-chevron-right fa-3x">
    {% endif %}
  </div>
</div>
{% endblock content %}

{% block extrajavascript %}
  {{ block.super }}
  <script src="{% static 'bower_components/jquery-sticky/jquery.sticky.js' %}"></script>
  <script>
    $("#sticky-menu").sticky({topSpacing:0, zIndex:100});

    function indicate_new_filters() {
      $("#sticky-menu").addClass("alert");
      $(".study-counts").addClass("study-counts-inactive");
      $("#message-bar").text("New filters have been selected. Click Apply to refresh studies.");
    }

    $(".domain-checkbox").on('change', indicate_new_filters);
    $('.study-counts').on('change', indicate_new_filters);

  </script>
  <script src="{% static 'bower_components/bokeh/bokeh-0.12.3.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'bower_components/bokeh/bokeh-widgets-0.12.3.min.js' %}"></script>
  {{ plot_summary_script|safe }}
{% endblock extrajavascript %}

studies/templates/studies/study_list.html
{% extends 'content.html' %}
{% load django_tables2 %}

{% block content %}
<div class="row buffer">
  <div class="large-11 columns">
    <h1 class="main-headline">Study List</h1>
  </div>
</div>
<div class="row buffer">
  <div class="large-11 columns">
    {% if user.is_staff %}
	<p>
	  To control the study fields shown in this list or the order of the columns, change the display order of any <a href="{% url 'admin:studies_studyfield_changelist' %}">study field</a>.
	</p>
	{% endif %}
<div class="row">
  <div class="large-11 columns">
    {% with table.page as page_obj %}
      {% include 'snippet_pagination.html' %}
    {% endwith %}
  {% render_table table %}
  </div>
</div>
{% endblock content %}

studies/templates/studies/variable_list.html
{% extends 'content.html' %}
{% load django_tables2 crispy_forms_tags static %}

{% block content %}
<div class="row">
  <div class="small-4 columns">
    <div class="sidebar">
      <h5>Qualifiers</h5>
      <ul class="side-nav">
        {% for qualifier in qualifiers %}
          <li><a href="{% url 'variable-list' qualifier.code %}">{{ qualifier.label }}</a></li>
        {% endfor %}
      </ul>
      <h5>Domains</h5>
      <ul class="side-nav">
        {% for domain in domains %}
          <li><a href="{% url 'variable-list' domain.code %}">{{ domain.label }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="small-8 columns">
    <h1 class="main-headline">
      {% if domain.is_qualifier %}Qualifier{% else %}Domain{% endif %}
      <small>{{ domain.label}} ({{ domain.code }})</small>
    </h1>
      {% crispy form form.helper %}
      {% with table.page as page_obj %}
        {% include 'snippet_pagination.html' %}
      {% endwith %}
      {% render_table table %}
  </div>
</div>
{% endblock content %}

{% block extrajavascript %}
{{ block.super }}
<script src="{% static 'bower_components/foundation/js/vendor/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'bower_components/jquery-ui/jquery-ui.js' %}" type="text/javascript" ></script>
<script>
$( "#id_variable" ).autocomplete({
  source: {{ form.variable_autocomplete_options|safe }},
  autoFocus: true,
});
</script>
{% endblock extrajavascript %}